---
title: "Untitled"
author: "Le Cai"
date: "2024-09-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
     
```



```{r}
library(tidyverse)
library(readr)
library(shiny)
library(glue)
library(bslib)
library(DT)
library(tmap)
#install.packages("tmap")
library(spData)
library(sf)
library(ggplot2)
data <- read_csv("https://uwmadison.box.com/shared/static/z6aapq6uw92xg4a31f96w9wd08fonv1j.csv")


```

Add a slider function to choose year

```{r}
scatterplot <- function(data, selected_) {
  data|>
    mutate(selected = selected_)|>
    ggplot() +
    #geom_map(data = map_data("world") , map = map_data("world"), aes(long, lat, map_id = region))+ # i think the app doesn't allow putting map since there's no variable in mapping that is a changing variable from brush
    #geom_sf(data=world, fill = "grey", color = "white") +
    geom_point(aes(lng, lat, color = rank, alpha = as.numeric(selected), size = as.numeric(selected))) +
  scale_alpha(range = c(0.1, 0.5), guide = "none")+
  scale_size(range = c(0.1, 5), guide = "none")+ # change dots' size
    labs(
    title = "Scatter Plot on Worlds Best Restaurants with Gradient Color Based on Rank",
    color = "Rank",
    alpha = "Rank",
    size = "Rank"
  )
    }

filter_df <- function(df, selected_) {
  filter(df, selected_) |>
    select(lng, lat, country,restaurant,year, rank)
}

ui <- fluidPage(
  h3("Worlds Best Restaurants"),
  plotOutput("map", brush = "plot_brush", height = 600),
  DTOutput("table")
  #theme = bs_theme(bootswatch = "minty")
)

server <- function(input, output) {
  selected <- reactiveVal(rep(TRUE, nrow(data)))
  observeEvent(input$plot_brush, {
    selected(brushedPoints(data, input$plot_brush, allRows = TRUE)$selected_)
  })
  
  output$map <- renderPlot(scatterplot(data, selected()))
  output$table <- renderDT(filter_df(data, selected()))
}

shinyApp(ui, server)


```



```{r}
plot(world%>%st_geometry())
color_palette <- colorRampPalette(c("darkblue","lightblue"))
point_colors <- color_palette(length(unique(data$rank)))[data$rank]
points(data$lng, data$lat, col = point_colors, pch = 19, cex = 0.7)
color_legend <- color_palette(100)  # Gradient colors for the legend
breaks <- pretty(data$rank, n = 10)
legend("bottomright", legend = breaks, fill = color_palette(100)[as.numeric(cut(breaks, breaks = 100))], 
       title = "Rank", cex = 0.8, bty = "n", border = "white", xpd = TRUE)

```


```{r}
world_coordinates <- map_data("world") 
  
# create world map using ggplot() function 
ggplot() + 
  
# geom_map() function takes world coordinates  
# as input to plot world map 
  geom_map( 
    data = world_coordinates, map = world_coordinates, 
    aes(long, lat, map_id = region) 
  )

```

```{r}
#world <- st_as_sf(world)
data_sf <- st_as_sf(data, coords = c("lng", "lat"), crs = 4326)
ggplot() +
  geom_sf(data = world, fill = "grey", color = "white") +
  # Overlay points with a gradient color based on 'rank'
  geom_sf(data = data_sf, aes(color = rank, alpha = rank, size = rank), shape = 19) +
  # Apply a color gradient scale to the points based on 'rank'
  scale_color_gradient(low = "darkblue", high = "lightblue") +  # Gradient for rank
  scale_alpha(range = c(0.1, 0.5), guide = "none") +  # Set transparency (alpha)
  scale_size(range = c(0.1, 0.9), guide = "none") +  # Set point sizes based on 'rank'
  coord_sf() +
  theme_void() +
  labs(
    title = "Scatter Plot on World Map with Gradient Color Based on Rank",
    color = "Rank",
    alpha = "Rank",
    size = "Rank"
  )
```


```{r}

```

```{r}
ggplot(data,aes(x=salary))+geom_histogram()
qqnorm(data$salary)
qqline(data$salary)

plot(data$work_year,data$salary)
m=lm(data$work_year~data$salary)
yint=m$coefficients[1]
xval=m$coefficients[2]
abline(a=yint,b=xval)
```

